# Generated by Django 6.0.4 on 2026-05-02 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activate_staff_superusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorlog',
            name='anomaly_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='authentication_outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('otp_required', 'OTP Required'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='autofill_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='avg_flight_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='avg_hold_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='correction_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='delete_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='device',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='double_click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='field_transition_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='hesitation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='hover_pattern_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='idle_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='idle_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='mouse_avg_speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='paste_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='pause_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='prediction_label',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='returning_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='submit_latency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='suspicious_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='timezone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='total_mouse_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='total_typing_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='behaviorlog',
            name='username_attempted',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
