# Generated by Django 6.0.4 on 2026-05-09 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_behaviorlog_anomaly_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('brute_force', 'Brute Force Attempt'), ('unusual_time', 'Unusual Login Time'), ('new_device', 'New Device Detected'), ('new_location', 'New IP/Location'), ('multiple_failures', 'Multiple Failed Attempts'), ('suspicious_behavior', 'Suspicious Behavior Pattern'), ('otp_brute_force', 'OTP Brute Force')], default='suspicious_behavior', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspicious Activity',
                'verbose_name_plural': 'Suspicious Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_su_user_id_1f2e63_idx'), models.Index(fields=['ip_address'], name='accounts_su_ip_addr_f98308_idx'), models.Index(fields=['is_resolved'], name='accounts_su_is_reso_6fe8e1_idx')],
            },
        ),
    ]
