# Generated by Django 6.0.4 on 2026-05-01 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField(default=0)),
                ('recall', models.FloatField(default=0)),
                ('f1_score', models.FloatField(default=0)),
                ('total_samples', models.IntegerField(default=0)),
                ('training_samples', models.IntegerField(default=0)),
                ('test_samples', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Model Metrics',
                'verbose_name_plural': 'Model Metrics',
                'ordering': ['-trained_at'],
            },
        ),
    ]
